name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        subscriptionIds: ["b85f94f2-f83b-476b-a9de-c3b7c82238de"]
    steps:
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS_A85B487E}}
        allow-no-subscriptions: true

    - name: Checkout
      uses: actions/checkout@v2 
      
    - name: Find and Replace
      uses: jacobtomlinson/gha-find-replace@master
      with:
        find: "{{SID}}"
        replace: ${{ matrix.subscriptionIds }}
        include: "policy.json"
        
    - name: Create or Update Azure Policies
      uses: azure/manage-azure-policy@v0
      with:      
        paths: |
          policies/Append_a_tag_and_its_value_from_the_resource_group_9ea02ca2-71db-412d-8b00-7c7ca9fcd32d/**
